name: Hexo Blog

on:
  workflow_dispatch:
  push:
    branches:
      - main  # default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js Environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: '19.0.0'
      - name: Cache NPM Dependencies
        uses: actions/cache@v3.2.2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Download Resume
        run: wget "https://docs.google.com/document/d/1Kf4SZogOunaaM5uOI8Z0a47yzBsE19vzO8xEE59pW9g/export?format=pdf" -O ./public/resume.pdf
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
